sonar.projectKey=morgantask
sonar.projectName=MorganTask
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

sonar.sources=morgantask_backend/src,morgantask_frontend/src
sonar.tests=morgantask_backend/src,morgantask_frontend/src

sonar.test.inclusions=\
  morgantask_backend/src/**/__tests__/**/*.test.ts,\
  morgantask_frontend/src/**/*.test.ts,\
  morgantask_frontend/src/**/*.test.tsx

sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/coverage/**,\
  morgantask_frontend/src/test/**

sonar.typescript.tsconfigPaths=tsconfig.json,morgantask_backend/tsconfig.json,morgantask_frontend/tsconfig.json
sonar.javascript.lcov.reportPaths=morgantask_backend/coverage/lcov.info,morgantask_frontend/coverage/lcov.info
